#!/usr/bin/env bash

JMETER_HOME="$1"

RESULT_FILE="$2"
EXPORT_DASHBOARD_HOME="$3"


rm -r $EXPORT_DASHBOARD_HOME
mkdir -p $EXPORT_DASHBOARD_HOME


$JMETER_HOME/bin/jmeter -g $RESULT_FILE -o $EXPORT_DASHBOARD_HOME

